DATASET:
  PATH:
    TFRECORDS : ['./park_dataset_demo/source','./park_dataset_demo/target/Target1','./park_dataset_demo/target/Target2']
    NORMAL : '/home/thanhho/SPARC/ESCA/Code/training_on_pc/Data/target/park/Target1/normal'
    ANOMALY : '/home/thanhho/SPARC/ESCA/Code/training_on_pc/Data/target/park/Target1/anomaly'
    # TEST: '/home/thanhho/SPARC/ESCA/Code/Data/dev_data_fan/fan/source_test/Normal'

TRAINING: 
  SAVE_PATH : '/home/minkescanor/Desktop/WORKPLACE/EDABK/Human Img Classify/results'
  EPOCH : 75

